In [7]:
import pandas as pd 

In [8]:
dataset = pd.read_csv('SalaryData.csv') # To load file

In [10]:
dataset.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [20]:
y = dataset['Salary']  # predection / To predict (label)

In [21]:
x = dataset ['YearsExperience']  # predector (Independent variable)

In [22]:
type(x)

pandas.core.series.Series

In [23]:
X = x.values.reshape(30,1) # converted to 2D as linear regression supports 2D array

In [24]:
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
model = LinearRegression()

# y = b + c x

In [27]:
# it knows : x & y
# it has to find: C(Coefficient) & b (bias)

model.fit(X,y)

LinearRegression()

In [50]:
model.predict([[1.1]])  # To predict

array([36187.15875227])

In [43]:
model.coef_ # to find weightage 'c'

array([9449.96232146])

In [47]:
model.intercept_  # To find bias

25792.20019866871

In [ ]:
#linear regression : linear algebera : linear function
# y = b + cx
# weight = c = coefficient 


In [51]:
y = 25792.20019866871 + 1.1*9449.96232146

In [52]:
y

36187.158752274714

In [53]:
import joblib

In [54]:
joblib.dump(model, 'salary_est_model.pk1')

['salary_est_model.pk1']